### ISSUE TITLE
BUG for build.py

### ISSUE THREAD

**Issue by ChenMiaoi** [ark-compiler/monorepo#1]
## What Happend?

**When I run the `build.py` to build the clang, I find this(the kernel patches' path) will lead to an error**.

``` bash
python3 ./toolchain/llvm-project/llvm-build/build.py \
	--no-build-arm \
	--no-build-aarch64 \
	--no-build-mipsel \
	--no-bulid windows
```

## Where the BUG?

I find the bug happend in the [build.py](https://github.com/ark-compiler/monorepo/blob/weekly_20230905/toolchain/llvm-project/llvm-build/build.py) at 939 lines

``` python
linux_kernel_dir = os.path.join('kernel_linux_patches', 'linux-5.10')
```

**But the real path is**`kernel/linux/patches`. So after I fix it, the `build.py` can run correctly.

``` python
# FIX: kernel_linux_patches -> 'kernel/linux/patches',
linux_kernel_dir = os.path.join('kernel/linux/patches', 'linux-5.10')
```

## Question

**I would like to ask if I should modify and submit the pr, and I can only ensure that the script runs correctly in `monorepo`**.

**Comment by brsvh** [comment]
````python
linux_kernel_dir = os.path.join('kernel_linux_patches', '
````
It seems that I forgot to create some necessary symbolic links.

See https://gitee.com/riscv-sig/arkcompiler-manifest/blob/master/llvm-toolchains.xml#L8

**Comment by brsvh** [comment]
I think you should create a proper symbolic link to fix the issue, rather than modifying the hard-coded path in the Python script.

**Comment by ChenMiaoi** [comment]
ok, I understand clearly
